application: omega-bearing-780
version: 2
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api_admin.*
  script: api_admin.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "latest"
